---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: petmotel-identity
  name: petmotel-identity
  namespace: petmotel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petmotel-identity
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: petmotel-identity
    spec:
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: regcred
      containers:
        - image: docker.io/binarybird/petmotel-identity
          name: petmotel-identity
          imagePullPolicy: Always
          resources: {}
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - mountPath: "/tls"
              name: tls
              readOnly: true
            - mountPath: "/rabbitmq"
              name: rabbitmq
              readOnly: true
      volumes:
        - name: tls
          secret:
            secretName: rabbitmq-tls-cert-secret
        - name: rabbitmq
          secret:
            secretName: petmotel-mq-default-user
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: petmotel-identity
  namespace: petmotel
  labels:
    run: petmotel-identity
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: petmotel-identity
  type: NodePort