apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rabbitmq-tls-cert
  namespace: petmotel
spec:
  secretName: rabbitmq-tls-cert-secret
  isCA: false
  usages:
    - server auth
    - client auth
  dnsNames: 
    - cluster.local
    - svc.cluster.local
    - petmotel.svc.cluster.local
    - petmotel-mq.petmotel.svc.cluster.local
    - petmotel-mq-nodes.petmotel.svc.cluster.local
    - petmotel-mq-server-0.petmotel.svc.cluster.local
  issuerRef:
    name: petmotel-tls-issuer
