version: '3.4'
services:
  petmotel-web:
    build:
      context: .
      dockerfile: services/PetMotel.Web/Dockerfile
    image: docker.io/binarybird/petmotel-web
  petmotel-identity:
    build:
      context: .
      dockerfile: services/PetMotel.Identity/Dockerfile
    image: docker.io/binarybird/petmotel-identity
  petmotel-basket:
    build:
      context: .
      dockerfile: services/PetMotel.Basket/Dockerfile
    image: docker.io/binarybird/petmotel-basket