version: '3.4'
services:
  petmotel-web:
    build:
      context: .
      dockerfile: PetMotelWeb/Dockerfile
    image: docker.io/binarybird/petmotel-web
  petmotel-identity:
    build:
      context: .
      dockerfile: services/Identity/Dockerfile
    image: docker.io/binarybird/petmotel-identity
  petmotel-basket:
    build:
      context: .
      dockerfile: services/Basket/Dockerfile
    image: docker.io/binarybird/petmotel-basket