apiVersion: v1
kind: Pod
metadata:
  name: petmotel-web
spec:
  imagePullSecrets:
    - name: regcred
  containers:
    - image: docker.io/binarybird/petmotelweb
      name: dotnetcoreapp
      imagePullPolicy: Always
      resources: {}
      ports:
        - containerPort: 80