apiVersion: v1
kind: Namespace
metadata:
  name: petmotel
---
apiVersion: apps/v1
kind: Deployment 
metadata: 
  creationTimestamp: null 
  labels: 
    app: petmotel-web 
  name: petmotel-web 
  namespace: petmotel
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: petmotel-web 
  strategy: {} 
  template: 
    metadata: 
      creationTimestamp: null 
      labels: 
        app: petmotel-web 
    spec: 
        dnsPolicy: ClusterFirst
        imagePullSecrets: 
          - name: regcred 
        containers: 
          - image: docker.io/binarybird/petmotel-web 
            name: petmotel-web
            imagePullPolicy: Always 
            resources: {} 
            ports: 
              - name: http
                containerPort: 80
status: {} 
---
﻿apiVersion: v1
kind: Service
metadata:
  name: petmotel-web
  namespace: petmotel
  labels:
    run: petmotel-web
spec:
  ports:
  - port: 80
    protocol: TCP
    name: http
  selector:
    app: petmotel-web
  type: NodePort
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: petmotel-web-ingress
  namespace: petmotel
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          serviceName: petmotel-web
          servicePort: 80
